### ISSUE TITLE
Task fails to save when Start Date is set to anytime before the day after tomorrow

### ISSUE THREAD

**Issue by murchu27** [Jeoxs/khanos#13]
Whenever I'm creating a new task, or modifying an existing one, the below error will appear if "Start Date" is set. The task saves successfully as long as "Start Date" is not set.

[UPDATE] This error only appears when "Start Date" is set to some time before the day after tomorrow. I tested this on August 30, and the screenshots below show that the task fails to save when "Start Date" is set to August 31 23:59, but succeeds when set to September 1 00:00. I tried many dates before August 31 23:59, and all failed. I also tried many dates after September 1 00:00, and all succeeded.

[UPDATE 2] Of course, I have also tested doing this through the Kanboard web client, and I can set any date from there.

Expected behaviour is to be able to set "Start Date" to any date, and for the task to save successfully.

I'm using:
Kanboard v1.2.20
Khanos v1.1.3

![Screenshot_20210830-103730_1](https://user-images.githubusercontent.com/24554361/131321049-a3ec5ffb-477e-4302-b717-3b064b043b11.jpg)
![Screenshot_20210830-104247_1](https://user-images.githubusercontent.com/24554361/131321055-98663218-d9c9-4540-ab2f-06bbaacc69fd.jpg)

**Comment by Jeoxs** [comment]
Hello! This is happening because of one validation in Kanboard's API Procedures. For what I can see, When you stablish a start date, you must set the Due Date, too. You can check it out here: [Kanboard's Github](https://github.com/kanboard/kanboard/blob/91d33b8dcb6bf802dba28aa5b0453c8f70a356e0/app/Validator/TaskValidator.php#L52). I couldn't replicate this on my end. My Kanboard instance allowed me to create the task without Due Date when setting a Start Date. Maybe, because of the Version difference (Mine is 1.2.14 while yours is 1.2.20). The other problem I see is that API procedures doesn't return the error message. It only returns false on error. 

One workaround here would be to make the Due/Start date a required field when one of the two are set. That way, the Instance won't run into problems when creating or updating the task. I'll put more thinking on this!

**Comment by murchu27** [comment]
Hey @Jeoxs , thanks for the suggestion, but I actually also get this error when Due Date is set. I can also set a Due Date without a Start Date, and this works just fine.

I'll try to dig into my logs whenever I get a chance to see if there's any clues there

**Comment by Jeoxs** [comment]
hey, @murchu27 I see! Then, the real issue is with another field. Yes, if you could check the logs, it would be great.

**Comment by murchu27** [comment]
Had a little bit of trouble getting the headers out of my logs to see what was being sent, but I did notice some more specific behaviour around when this fails. I'm going to update the issue description now.

**Comment by Jeoxs** [comment]
Hey! I'm trying to replicate this specifying a start day of Tomorrow at 23:59 but the API allows me to create/update it. I'll keep digging to see why it fails on your end with that specific condition

**Comment by murchu27** [comment]
That's weird... if I get a chance, I'll try curl my endpoint to see the response that way, as I'm still not sure how to see the headers of requests in my Apache log.

The two API endpoints used are `createTask` and `updateTask`, yeah?

**Comment by Jeoxs** [comment]
Hey @murchu27 ! Yes, the API methods are createTask and updateTask. Most of the fields are optional.

**Comment by murchu27** [comment]
So the methods worked fine when I requested them with curl, and then when I went back to try on the app, all of a sudden that was working fine. No idea what the problem was here.

I'm going to close this. If someone else has the same problem as me later, we can reopen it and review.

**Comment by jtejido** [comment]
It's a problem with the date format used in the /pages/task_form.dart....the backend api accepts MM/dd/yy but the form is submitting it as dd/MM/yy
